version: "3.9"
services: 
    minecraft_server:
      image: itzg/minecraft-server:java8
      ports:
        - 25565:25565
      environment:
        EULA: "TRUE"
        VERSION: "1.12.2"
        TYPE: "FORGE"
      deploy:
        resources:
          limits:
            memory: 1.5G
      volumes:
        - /home/gink_official01/data:/data
 
    webmine:
        build: .
        ports: 
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
            - /home/gink_official01/data:/go/src/webmine/data
        restart: always
        env_file:
            - production.env